### ISSUE TITLE
CI/CD build broken

### ISSUE THREAD

**Issue by dejan-xd** [dejan-xd-organization/NistagramBackend#4]
Investigate why build is broken and fix it.

**Comment by jovan92** [comment]
Rešen je problem što se tiče broken CI build-a. Imao sam problema sa dotnet restore, build i test ali je sve namešteno sad. Takođe sam i proširio CI.yml fajl sa docker CI.

**Comment by dejan-xd** [comment]
Ubio sam da provalim šta je problem sa buildom. Koliko vidim to je problem koji datira od pre par godina i ne rešava se. Mislim da je problem sa VS, NuGet, i Git-om.
Pretražio sam boga oca linkova, nema šta nisam probao (zatrpao sam develop granu bezveze) i ništa nije uspelo.
Sklonio sam build iz CI.yml i ostavićemo to kao rešenje.
